nursery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('plants/', views.PlantListView.as_view(), name='plants'),
    path('plant/<int:pk>', views.PlantDetailView.as_view(), name='plant-detail'),
    path('plantinstances/', views.PlantInstanceStaffOnlyListView.as_view(), name='plantinstances'),
    path('plantinstance/<uuid:pk>', views.PlantInstanceDetailView.as_view(), name='plant-instance-detail'),
    path('locations/', views.LocationListView.as_view(), name='locations'),
    path('mylocations/', views.LocationByUserListView.as_view(), name='my-locations'),
    path('location/<int:pk>', views.LocationDetailView.as_view(), name='location-detail'),
]

urlpatterns += [
    path('myplanttemplates/', views.PlantByUserListView.as_view(), name='user-plant-templates'),
    path('myplants/', views.PlantInstanceByUserListView.as_view(), name='my-plants'),
    path('myduewateredplants/', views.DueWateredPlantsByUserListView.as_view(), name='my-due-watered'),
]

urlpatterns += [
    path('plant/<uuid:pk>/renew_due_watered/', views.renew_due_watered_date, name='renew-due-watered-date'),
]

urlpatterns += [ 
    path('plant/create/', views.PlantCreate.as_view(), name='plant-create'), 
    path('plant/<int:pk>/update/', views.PlantUpdate.as_view(), name='plant-update'), 
    path('plant/<int:pk>/delete/', views.PlantDelete.as_view(), name='plant-delete'),
    path('location/create/', views.LocationCreate.as_view(), name='location-create'),
    path('location/<int:pk>/update/', views.LocationUpdate.as_view(), name='location-update'), 
    path('location/<int:pk>/delete/', views.LocationDelete.as_view(), name='location-delete'),]

urlpatterns += [ 
    path('plantinstance/create/', views.PlantInstanceCreate.as_view(), name='plant-instance-create'),
    path('plantinstance/<int:pk>/create/', views.PlantInstanceCreateFromPlant.as_view(), name='plant-instance-create-from-plant'),
    path('plantinstanceloc/<int:pk>/create/', views.PlantInstanceCreateFromLocation.as_view(), name='plant-instance-create-from-location'),
    path('plantinstance/<uuid:pk>/update/', views.PlantInstanceUpdate.as_view(), name='plant-instance-update'), 
    path('plantinstance/<uuid:pk>/delete/', views.PlantInstanceDelete.as_view(), name='plant-instance-delete'),]

urlpatterns += [
    path('staff/location/<int:pk>/update/', views.LocationUpdateStaffOnly.as_view(), name='staff-location-update'),
    path('staff/plant/<int:pk>/update/', views.PlantUpdateStaffOnly.as_view(), name='staff-plant-update'),
    path('staff/plantinstance/<uuid:pk>/update/', views.PlantInstanceUpdateStaffOnly.as_view(), name='staff-plant-instance-update'), 
]

petrichor/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the nursery application
from django.urls import include
# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nursery/', include('nursery.urls')),
    # redirect root URL (i.e., 127.0.0.1:8000) to the URL 127.0.0.1:8000/nursery/
    path('', RedirectView.as_view(url='nursery/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

nursery/models.py
from django.db import models
from django.urls import reverse # Used in get_absolute_url() to get URL for specified ID
from django.db.models import UniqueConstraint # Constrains fields to unique values
from django.db.models.functions import Lower # Returns lower cased value of field
import uuid # Required for unique plant instances
from django.conf import settings
from django.contrib.auth.models import User
from datetime import date

class Location(models.Model):
    """Model representing a Location (e.g. Living Room, Kitchen, etc.)"""
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=50,
                            help_text="Enter the plant's Location (e.g. Living Room, Kitchen, etc.)")

    def get_absolute_url(self):
        """Returns the url to access a particular location instance."""
        return reverse('location-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

    class Meta:
        ordering = ['user', 'name']
        constraints = [models.UniqueConstraint(fields=['user', 'name'], 
                                               name='unique_name_per_owner')]

class Plant(models.Model):
    """Model representing a type of plant."""
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    scientific_name = models.CharField(max_length=200)
    common_name = models.CharField(max_length=200, help_text="Select a common name for this plant", null=True)
    
    WATER_FREQ = (
        ('f', 'frequent'),
        ('r', 'regular'),
        ('i', 'infrequent'),
    )

    SUN = (
        ('f', 'full sun'),
        ('fp', 'full sun to part shade'),
        ('p', 'part shade'),
        ('ps', 'part shade to full shade'),
        ('sh', 'full shade'),
    )

    water = models.CharField(
        max_length=1,
        choices=WATER_FREQ,
        blank=False,
        help_text='watering frequency',
    )
    sun = models.CharField(
        max_length=2,
        choices=SUN,
        blank=False,
        help_text='sun light preference',
    )

    #image = models.ImageField(upload_to='Plants')

    description = models.TextField(max_length=1000, help_text="Enter a brief description of the plant")
    
    care_tips = models.TextField(max_length=1000, help_text="Enter a few care tips for the plant")

    class Meta:
        ordering = ['user']
        constraints = [
            models.UniqueConstraint(fields=['user', 'scientific_name'], name='unique_plant_scientificname_per_owner')
        ]

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.scientific_name}'

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this plant."""
        return reverse('plant-detail', args=[str(self.id)])

class PlantInstance(models.Model):
    """Model representing an instance of a type of plant."""
    plant = models.ForeignKey(Plant, on_delete=models.RESTRICT, null=True)
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    nickname = models.CharField(max_length=200, help_text='what do you call your plant child')
    
    # Foreign Key used because plant can only have one location, but location can house multiple plants.
    # location as a string rather than object because it hasn't been declared yet in file.
    location = models.ForeignKey(Location, on_delete=models.RESTRICT, null=True, help_text='location plant will live')
    
    purchased = models.DateField(null=True, blank=True, help_text='date plant was purchase')
    due_watered = models.DateField(null=True, blank=True, help_text='next watering date')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular plant across whole nursery")
    
    @property
    def is_overdue_watered(self):
        """Determines if the plant is overdue to be watered on due date and current date."""

        return bool(self.due_watered and (date.today() >= self.due_watered))

    class Meta:
        ordering = ['customer','nickname']
        constraints = [
            models.UniqueConstraint(fields=['customer', 'nickname'], name='unique_plantinstance_nickname_per_customer')
        ]

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.nickname} ({self.plant.scientific_name}) {self.id}'
    
    def display_common_name(self):
        """Create a string for common_name. This is required to display common_name in Admin."""
        return self.plant.common_name
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this plant instance"""
        return reverse('plant-instance-detail', args=[str(self.id)])

    display_common_name.short_description = 'Common Name'

nursery/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewDueWateredDateForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 2).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

nursery/templates/nursery/location_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ location.name }}</h1>
  <ul>
    <li><a href="{% url 'plant-instance-create-from-location' location.id %}">Add Plant to this Location</a></li>
  </ul>
  <div style="margin-left:20px;margin-top:20px">
    {% if  plantinstance_list %}
      <h4>All Plants in this Room</h4>
      {% for purchasedPlant in plantinstance_list %}
        <hr />
        {% if user.is_staff %} 
          <p><strong>*~STAFF VIEW~*</strong></p>
          <p><strong>Owner:</strong> {{ purchasedPlant.customer }}</p>
        {% endif %}
        <p><strong>Nickname:</strong> <a href="{{ purchasedPlant.get_absolute_url }}">{{ purchasedPlant.nickname }}</a></p>
        <p><strong>Plant:</strong> <a href="{{ purchasedPlant.plant.get_absolute_url }}">{{ purchasedPlant.plant.scientific_name }}</a></p>
        <p>
          <strong>Due to be watered:</strong> 
          <span class="{% if purchasedPlant.is_overdue_watered %}text-danger{% else %}text-success{% endif %}">
            {{ purchasedPlant.due_watered }}
          </span>
        </p>
      {% endfor %}
    {% else %}
        <h4>There are no Plants in this Location</h4>
    {% endif %}
  </div>
{% endblock %}

{% block sidebar %} 
  {{ block.super }} 
  {% if perms.nursery.change_location or perms.nursery.delete_location %} 
    <hr> 
    <ul class="sidebar-nav"> 
      {% if user.is_staff %}
        <li>*~STAFF VIEW~*</li> 
        <li><a href="{% url 'staff-location-update' location.id %}">Edit Location</a></li>
      {% elif perms.nursery.change_location %} 
        <li><a href="{% url 'location-update' location.id %}">Edit Location</a></li> 
      {% endif %}
       
      {% if not location.plantinstance_set.all and perms.nursery.delete_location %} 
        <li><a href="{% url 'location-delete' location.id %}">Delete Location</a></li>
      {% else %}
        <li><s>Delete Location</s></li> 
      {% endif %} 
      {% if user.is_staff %}
        <li>*~~~~~~~~~*</li>
      {% endif %}
    </ul> 
  {% endif %} 
{% endblock %}

nursery/templates/nursery/location_form.html
{% extends "base_generic.html" %} 

{% block content %} 
<form action="" method="post"> 
    {% csrf_token %} 
    <table> 
        {{ form.as_table }} 
    </table> 
    <input type="submit" value="Submit" /> 
</form> 
{% endblock %}

nursery/templates/nursery/location_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>List of All Locations</h1>
  {% if location_list %}
    <ul>
      {% for location in location_list %}
      <li>
        {{ location.user }} - <a href="{{ location.get_absolute_url }}">{{ location.name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no locations in the nursery.</p>
  {% endif %}
{% endblock %}

nursery/templates/nursery/location_list_by_user.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Locations</h1>
  <ul>
    <li><a href="{% url 'location-create' %}">Add Location to Garden</a></li>
  </ul>
  {% if location_list %}
    <ul>
      {% for loc in location_list %}
        <li>
            {{ loc.user }} - <a href="{{ loc.get_absolute_url }}">{{ loc.name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no Locations in Garden.</p>
  {% endif %}
{% endblock %}

nursery/templates/nursery/plant_confirm_delete.html
{% extends "base_generic.html" %} 

{% block content %} 

<h1>Delete Plant: {{ plant }}</h1> 

{% if plant.plantinstance_set.all %} 
<p>You can't delete this plant until all their plant instances have been deleted:</p> 
<ul> 
    {% for plantinst in plant.plantinstance_set.all %} 
    <li>
        <a href="{% url 'plant-instance-detail' plantinst.pk %}">{{plantinst.nickname}}</a> ({{plantinst.plant.plantinstance_set.all.count}})
    </li> 
    {% endfor %} 
</ul> 
{% else %} 
<p>Are you sure you want to delete the plant?</p> 
<form action="" method="POST"> 
    {% csrf_token %} 
    <input type="submit" action="" value="Yes, delete."> 
</form> 
{% endif %} 

{% endblock %}

nursery/templates/nursery/plant_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ plant.scientific_name }}</h1>
  <p><strong>Owner</strong> 
    {% if user == plant.user %}
      <span>Me</span>
    {% else %} 
      {{ plant.user }}
    {% endif %}
  </p>
  <p><strong>Common Name:</strong> {{ plant.common_name }}</p>
  <p><strong>Water:</strong> {{ plant.get_water_display }}</p>
  <p><strong>Sun:</strong> {{ plant.get_sun_display }}</p>
  <p><strong>Description:</strong> {{ plant.description }}</p>
  <p><strong>Care Tips:</strong> {{ plant.care_tips }}</p>

  
  <div style="margin-left:20px;margin-top:20px">
    <h4>Plants of this kind in My Garden</h4>
    {% if plantinstance_list %}
        {% for plantinst in plantinstance_list %}
        <hr />
        {% if user.is_staff %} 
          <p><strong>*~STAFF VIEW~*</strong></p>
          <p><strong>Owner:</strong> {{ plantinst.customer }}</p>
        {% endif %}
        <p><strong>Nickname:</strong> <a href="{{ plantinst.get_absolute_url }}">{{ plantinst.nickname }}</a></p>
        <p><strong>Location:</strong> <a href="{{ plantinst.location.get_absolute_url }}">{{ plantinst.location }}</a></p>
        <p><strong>Due to be watered:</strong>
          <span class="{% if plantinst.is_overdue_watered %}text-danger{% elif not plantinst.is_overdue_watered %}text-success{% else %}text-warning{% endif %}">
            {{ plantinst.due_watered }}
          </span>
          {% if plantinst.is_overdue_watered %}
            - <a href="{% url 'renew-due-watered-date' plantinst.id %}">Water</a>
          {% endif %} 
        </p>
      {% endfor %}
    {% else %}
        <hr>
        <p><strong>There are no Plants of this kind in My Garden</strong></p>
    {% endif %}
  </div>
{% endblock %}

{% block sidebar %} 
  {{ block.super }} 
  {% if perms.nursery.change_plant or perms.nursery.delete_plant %} 
    <hr> 
    <ul class="sidebar-nav"> 
      {% if perms.nursery.add_plant and not user.is_staff %} 
        <li><a href="{% url 'plant-instance-create-from-plant' plant.id %}">Add to My Garden</a></li> 
      {% endif %}
      {% if user.is_staff %}
        <li>*~STAFF VIEW~*</li> 
        <li><a href="{% url 'staff-plant-update' plant.id %}">Edit Plant</a></li>
        <li><a href="{% url 'plant-instance-create-from-plant' plant.id %}">Create Plant Instance</a></li>  
      {% elif perms.nursery.change_plant %} 
        <li><a href="{% url 'plant-update' plant.id %}">Edit Plant</a></li> 
      {% endif %}
       
      {% if not plant.plantinstance_set.all and perms.nursery.delete_plant %} 
        <li><a href="{% url 'plant-delete' plant.id %}">Delete Plant</a></li>
      {% else %}
        <li><s>Delete plant</s></li> 
      {% endif %} 
      {% if user.is_staff %}
        <li>*~~~~~*</li>
      {% endif %}
    </ul> 
  {% endif %} 
{% endblock %}

nursery/templates/nursery/plant_form.html
{% extends "base_generic.html" %} 

{% block content %} 
<form action="" method="post"> 
    {% csrf_token %} 
    <table> 
        {{ form.as_table }} 
    </table> 
    <input type="submit" value="Submit" /> 
</form> 
{% endblock %}

nursery/templates/nursery/plant_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>List of All Plant Templates Currently in Nursery</h1>
  {% if plant_list %}
    <ul>
      {% for plant in plant_list %}
      <li>
        {{ plant.user }} - 
        <a href="{{ plant.get_absolute_url }}">{{ plant.scientific_name }}</a>
        ({{ plant.common_name.all|join:", " }})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no plants in the nursery.</p>
  {% endif %}
{% endblock %}

nursery/templates/nursery/plant_list_by_user_and_groundskeep.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Plants in Nursery</h1>
  <ul>
    <li><a href="{% url 'plant-create' %}">Add Plant to Nursery</a></li>
  </ul>
  {% if plant_list %}
    <ul>
      {% for plant in plant_list %}
      <li>
        <a href="{{ plant.get_absolute_url }}">{{ plant.scientific_name }}</a>
        ({{ plant.common_name }})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no Plants in Nursery.</p>
  {% endif %}
{% endblock %}

nursery/templates/nursery/plantinstance_confirm_delete.html
{% extends "base_generic.html" %} 

{% block content %} 

<h1>Delete Plant: {{ plantinstance.nickname }}</h1> 
 
<p>Are you sure you want to delete this Plant?</p> 
<form action="" method="POST"> 
    {% csrf_token %} 
    <input type="submit" action="" value="Yes, delete."> 
</form>  

{% endblock %}

nursery/templates/nursery/plantinstance_form.html
{% extends "base_generic.html" %} 

{% block content %} 
<form action="" method="post"> 
    {% csrf_token %} 
    <table> 
        {{ form.as_table }} 
    </table> 
    <input type="submit" value="Submit" /> 
</form> 
{% endblock %}

nursery/templates/nursery/plantinstance_list_plants_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Plants</h1>
    <ul>
      <li><a href="{% url 'plant-instance-create' %}">Add Plant to My Garden</a></li>
      <li><a href="{% url 'my-due-watered' %}">All Dry Plants</a></li>
    </ul>
    {% if plantinstance_list %}
    <ul>

      {% for plantinst in plantinstance_list %}
      <li class="{% if not plantinst.is_overdue_watered %}text-success{% elif plantinst.is_overdue_watered %}text-danger{% endif %}">
        <a href="{% url 'plant-instance-detail' plantinst.pk %}">{{ plantinst.nickname }}</a> ({{ plantinst.due_watered }}) 
        {% if plantinst.is_overdue_watered %}- <a href="{% url 'renew-due-watered-date' plantinst.id %}">Water</a>{% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no plants.</p>
    {% endif %}
{% endblock %}

nursery/templates/nursery/plantinstance_list_staff_only.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Plant Instance List</h1>
  {% if plantinstance_list %}
    <ul>
      {% for plantinst in plantinstance_list %}
      <li>
        {{ plantinst.customer }} - <a href="{{ plantinst.get_absolute_url }}">{{ plantinst.nickname }} ({{ plantinst.plant }})</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no plant instances to show.</p>
  {% endif %}
{% endblock %}

nursery/templates/nursery/plantinstance_list_watered_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Watered Plants</h1>

    {% if plantinstance_list %}
    <ul>

      {% for plantinst in plantinstance_list %}
      <li class="{% if plantinst.is_overdue_watered %}text-danger{% endif %}">
        <a href="{% url 'plant-detail' plantinst.plant.pk %}">{{ plantinst.nickname }}</a> ({{ plantinst.due_watered }}) 
        {% if plantinst.is_overdue_watered %}- <a href="{% url 'renew-due-watered-date' plantinst.id %}">Water</a>{% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no watered plants.</p>
    {% endif %}
{% endblock %}